backend:
  name: github
  repo: onnenon/vcp # Path to your GitHub repository
  branch: main
  base_url: https://vcp.onnen.dev
  auth_endpoint: /api/auth

collections:
  - name: "multiple_choice_questions"
    label: "Multiple Choice Questions"
    label_singular: MC Question
    folder: "src/content/multiChoiceQuestions"
    create: true
    extension: json
    format: json
    identifier_field: question
    fields:
      - { label: "Question", name: "question", widget: "text" }
      - { label: "A", name: "choice_a", widget: "string" }
      - { label: "B", name: "choice_b", widget: "string" }
      - { label: "C", name: "choice_c", widget: "string" }
      - { label: "D", name: "choice_d", widget: "string" }
  - name: "tf_choice_questions"
    label: "True/False Questions"
    label_singular: T/F Question
    folder: "src/content/tfQuestions"
    create: true
    extension: json
    format: json
    identifier_field: question
    fields:
      - { label: "Question", name: "question", widget: "text" }
media_folder: "src/assets/images"
public_folder: "src/assets/images"
