backend:
  name: github
  repo: onnenon/vcp # Path to your GitHub repository
  branch: main
  base_url: https://vcp.onnen.dev
  auth_endpoint: /api/auth

collections:
  - name: "questions" # Used in routes, e.g., /admin/collections/blog
    label: "Questions" # Used in the UI
    folder: "src/content/questions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: json
    format: json
    fields: # The fields for each document, usually in frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "question",
        }
      - { label: "Question", name: "question", widget: "text" }
      - {
          label: "Answer Choices",
          name: "choices",
          widget: "list",
          min: 4,
          max: 4,
        }
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
