backend:
  name: github
  repo: onnenon/vcp # Path to your GitHub repository
  branch: main
  base_url: https://vcp.onnen.dev
  auth_endpoint: /api/auth

collections:
  - name: "multiple_choice_questions"
    label: "Survey Multiple Choice Questions"
    label_singular: Survey Multi-choice Question
    folder: "src/content/multi_choice_questions"
    create: true
    extension: json
    format: json
    identifier_field: question
    fields:
      - { label: "Question", name: "question", widget: "text" }
      - { label: "Answer Choice A", name: "choice_a", widget: "text" }
      - { label: "Answer Choice B", name: "choice_b", widget: "text" }
      - { label: "Answer Choice C", name: "choice_c", widget: "text" }
      - { label: "Answer Choice D", name: "choice_d", widget: "text" }
  - name: "tf_choice_questions"
    label: "Survey True/False Questions"
    label_singular: "True/False Question"
    folder: "src/content/tf_questions"
    create: true
    extension: json
    format: json
    identifier_field: question
    fields:
      - { label: "Question", name: "question", widget: "text" }
media_folder: "src/assets/images"
public_folder: "src/assets/images"
